#

GET http://localhost:8085/wharehouse/owners

###

GET http://localhost:8085/wharehouse/owners/active

###

GET http://localhost:8085/wharehouse/owners/1/items

###

DELETE http://localhost:8085/wharehouse/owners/delete/1

###

GET http://localhost:8085/wharehouse/items

###

GET http://localhost:8085/wharehouse/items/lastMonth

###

POST http://localhost:8085/wharehouse/owners
Content-Type: application/json

{
  "login": "nika11111",
  "firstName": "Nika",
  "lastName": "Lysenko",
  "companyName": "Cartoon",
  "contactsList": [
    {
      "contact": "098",
      "contactType": "mobilePhone"
    },
    {
      "contact": "098",
      "contactType": "mobilePhone"
    }
  ]
}

###

POST http://localhost:8085/wharehouse/owners/1/contacts
Content-Type: application/json

{
  "contact": "klysen@gmail.com",
  "contactType": "public email"
}

###

POST http://localhost:8085/wharehouse/items/1/10
Content-Type: application/json


###

POST http://localhost:8085/wharehouse/items/withdraw
Content-Type: application/json

{
  "1": "10",
  "2": "10"
}


###

POST http://localhost:8085/wharehouse/owners/1/items
Content-Type: application/json

{
  "title": "dress",
  "price": 100.00,
  "itemHistories": [
    {
      "date": "17/09/2019 06:36",
      "count": 20
    }
  ],
  "categories": [
    {
      "categoryTitle": "clothes",
      "description": "some description"
    }
  ]
}

###