DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ITEM_CATEGORY;
DROP TABLE IF EXISTS OWNER;
DROP TABLE IF EXISTS OWNER_CONTACTS;
DROP TABLE IF EXISTS ITEM_HISTORY;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE ITEM (
       ID INT NOT NULL AUTO_INCREMENT
     , TITLE VARCHAR(40) NOT NULL
     , PRICE DECIMAL(10,2)
     , OWNER_ID INT NOT NULL
     , UNIQUE UQ_ITEM_1 (TITLE)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_ITEM_OWNER_1 FOREIGN KEY (OWNER_ID)
                  REFERENCES OWNER (ID) ON DELETE CASCADE
);


CREATE TABLE CATEGORY (
       ID INT NOT NULL AUTO_INCREMENT
     , TITLE VARCHAR(20)
     , DESCRIPTION VARCHAR(160)
     , UNIQUE UQ_CATEGORY_1 (TITLE)
     , PRIMARY KEY (ID)
);

CREATE TABLE ITEM_CATEGORY (
       ITEM_ID INT NOT NULL
     , CATEGORY_ID INT NOT NULL
     , PRIMARY KEY (ITEM_ID, CATEGORY_ID)
     , CONSTRAINT FK_ITEM_CATEGORY_1 FOREIGN KEY (ITEM_ID)
                  REFERENCES ITEM (ID) ON DELETE CASCADE
     , CONSTRAINT FK_ITEM_CATEGORY_2 FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (ID) ON DELETE CASCADE
);

CREATE TABLE OWNER (
       ID INT NOT NULL AUTO_INCREMENT
     , LOGIN VARCHAR(16) NOT NULL
     , FIRST_NAME VARCHAR(16) NOT NULL
     , LAST_NAME VARCHAR(16)
     , COMPANY_NAME VARCHAR(100)
     , UNIQUE UQ_OWNER_1 (LOGIN)
     , PRIMARY KEY (ID)
);

CREATE  TABLE OWNER_CONTACTS (
       ID INT NOT NULL AUTO_INCREMENT
     , OWNER_ID INT NOT NULL
     , CONTACT VARCHAR(16) NOT NULL
     , CONTACT_TYPE VARCHAR(16) NOT NULL
     , PRIMARY KEY (ID)
	 , CONSTRAINT FK_OWNER_CONTACTS_1 FOREIGN KEY (OWNER_ID)
                  REFERENCES OWNER (ID) ON DELETE CASCADE
);

CREATE TABLE ITEM_HISTORY (
        ID INT NOT NUll AUTO_INCREMENT
      , ITEM_ID INT NOT NULL
     , DATE DATETIME
     , COUNT int
     , STATUS VARCHAR(16) NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_ITEM_HISTORY_1 FOREIGN KEY (ITEM_ID)
                  REFERENCES ITEM (ID) ON DELETE CASCADE
);